disabled_rules: # rule identifiers to exclude from running
   - trailing_whitespace
   - force_try
   - function_body_length
   - type_body_length
   - cyclomatic_complexity
   - function_parameter_count
   - force_cast
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Tests
vertical_whitespace:
  severity: error